title: RyanWillDev
author: Ryan Will
email: ryanwilldev@gmail.com
url: 'https://www.ryanwill.dev'
description: 'Cultivating ideas and software with varying degrees of success'

permalink: "/rants/:title"

favicon: "favicon.ico"

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%B %d, %Y"
  show_description: true
  lowercase_titles: true

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"

highlighter: rouge
kramdown:
  input: GFM
markdown: kramdown

sass:
  load_paths:
    - _sass
  style: compressed
  silence_deprecations:
    - import

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

